### ISSUE TITLE
全是干货，要是配上视频或者录音，就完美了。

### ISSUE THREAD

**Issue by vc60er** [rfyiamcool/share_ppt#10]
全是干货，要是配上视频或者录音，就完美了。

**Comment by rfyiamcool** [comment]
😅

**Comment by zpng** [comment]
的确，同求录音或视频，不然光看感觉有些迷茫

**Comment by rfyiamcool** [comment]
其实就是为了后期的文章和视频，所以尽量在ppt里多一些信息。😅 但描述性还是差一点。
同事做过视频，采集的视频和语音太差劲了，索性就放弃了。
后面有时间会搞成文字模式。

**Comment by BillZong** [comment]
在 git 里边存音视频文件太大了，每一次有新的提交都拉不下来的感觉~
建议还是只放文字就好。
还是要感谢大佬的分享！
