### ISSUE TITLE
为什么要减少使用pub sub?

### ISSUE THREAD

**Issue by TenzT** [rfyiamcool/share_ppt#20]

**Comment by rfyiamcool** [comment]
你说的是推送系统吧，pubsub虽然让推送系统的架构更加简单，但在消息频繁的场景下，会产生惊群的问题。

比如 当前有10个pusher节点，而客户端a连接到了pusher1，使用pubsub进行消息发送订阅的话，所有的pusher都收到该消息，然后在本节点中寻找对应的连接。 也就是说，只有push1有效，其他节点做无用功。

我们在上个月优化了方案，可通过gossip或者redis来定位pusher节点，业务发送端采用grpc的方式直接丢给pusher1。
