### ISSUE TITLE
gev & gnet 选择

### ISSUE THREAD

**Issue by samuelyao314** [rfyiamcool/share_ppt#21]
golang分布式消息推送系统,  这个系统里，
为什么用 https://github.com/Allenxuxu/gev ？ 而不是用 https://github.com/panjf2000/gnet

**Comment by rfyiamcool** [comment]
哈哈，我在ppt里有说过，gev和gnet的实现差不多，不管是性能和架构上都满足了我的要求。选择gev是因为我跟gev的徐旭是前同事。另外，gev里自带了websocket协议解析，如果用gnet或者其他rawepoll框架，还需要花费点时间搞定协议层。

**Comment by lesismal** [comment]
nbio网络库部分性能应该更强一些，而且对tls/http1x/websocket做了更完善的支持。。
以后如果有契机，欢迎试用。。:joy::smile:

**Comment by rfyiamcool** [comment]
@lesismal  老板的 nbio 我一直有关注，实现很全面，该有的都有，别人没有的你也有，协议很全，另外安全的tls也加入了。 后面公司有个新项目可以用用 nbio 。😁

**Comment by lesismal** [comment]
> bio 我一直有关注，实现很全面，该有的都有，别人没有的你也有，协议很全，另外安全的tls也加入了。 后面公司有个新项目可以

感谢老板支持！

**Comment by lesismal** [comment]
kitex 自己的，我pr进去了：
https://github.com/cloudwego/kitex-benchmark

鸟窝那个帖子我留言都删除了，伤心了，等你看到这个我把这条也删掉

![image](https://user-images.githubusercontent.com/40462947/128709872-1844c8e4-9399-456f-8c35-965c2bacca6d.png)
