### ISSUE TITLE
请问PPT里的图是直接用Keynote画的吗？

### ISSUE THREAD

**Issue by mupengX** [rfyiamcool/share_ppt#25]
RT，比如《分布式行情推送系统》这个PPT里定时器优化那些图是用的什么工具呀，另外这个Keynote的模板是淘宝上淘的吗？系统自带的模板里没找到，可不可以分享一下PPT里常用的模板是哪些🤠

**Comment by rfyiamcool** [comment]
我现在基本用keynote默认的模板, 尤其是那个黑板, 图就是用keynote的图形来画的，很是麻烦。。。。😅
