### ISSUE TITLE
作者在哪个平台分享的啊

### ISSUE THREAD

**Issue by NeoZephyr** [rfyiamcool/share_ppt#36]

**Comment by rfyiamcool** [comment]
在极客时间里做过一些视频分享，有兴趣可以看看.

https://time.geekbang.org/qconplus/detail/100110489

**Comment by rfyiamcool** [comment]
先前跟一个平台合作，搞了一波网络编程的视频，结果那平台倒闭了.   后面因为电脑硬盘损坏无法恢复视频，导致没法放到 B 站分享给大家了，十分可惜. 😁

**Comment by NeoZephyr** [comment]
那确实可惜啊！后续有可能继续做技术分享吗
