### ISSUE TITLE
关于网络编程那些事儿PPT

### ISSUE THREAD

**Issue by kuangtu** [rfyiamcool/share_ppt#37]
感谢作者的分享，非常精彩！
在阻塞vs非阻塞比对那页，有个笔误：
非阻塞--》发送缓冲区没满，第二种场景，应该是“剩余空间**不够**写下所有数据”---》能写多少是多少，然后返回报错EAGAIN。
另外，对于返回，建议可以说明是返回检查errno，不是send调用本身的返回，新手可能容易理解错。

**Comment by rfyiamcool** [comment]
哈哈，好的.
